{% set data = load_setup_py_data(setup_file='setup.py') %}

package:
  name: ising-glass-annealer
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 3
 
requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - numpy
    - scipy

  run:
    - gcc_impl_linux-64
    - python
    - numpy
    - scipy
