{% set data = load_setup_py_data(setup_file='setup.py') %}

package:
  name: ising-glass-annealer
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0

test:
  requires:
    - h5py
    - pytest
  source_files:
    - "*.h5"
    - run_tests.py
  commands:
    - python -m pytest run_tests.py

requirements:
  build:
    - {{ compiler('c') }}
    - gmp
    - libffi
    # - numactl-devel-cos7-x86_64 # [linux]

  host:
    - python
    - pip
    - cffi>=1.15
    - numpy
    - scipy

  run:
    - python
    - cffi>=1.15
    - numpy
    - scipy
    # Runtime libraries needed the Haskell code
    - gmp
    - libffi
      # - numactl-libs-cos7-x86_64 # [linux]
    - sysroot_linux-64 # [linux]
