{% set data = load_setup_py_data(setup_file='setup.py') %}

package:
  name: ising-glass-annealer
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  run_exports:
    - python
  ignore_run_exports:
    - numpy
    - scipy
    - numactl-libs-cos7-x86_64 # [linux]
    - sysroot_linux-64 # [linux]
 
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi>=1.15
    - numpy
    - scipy
    - gmp
    - libffi
    - numactl-devel-cos7-x86_64 # [linux]
  run:
    - cffi>=1.15
    - numpy
    - scipy
    # Runtime libraries needed the Haskell code
    - gmp
    - libffi
    - numactl-libs-cos7-x86_64 # [linux]
    - sysroot_linux-64 # [linux]