{% set data = load_setup_py_data(setup_file='setup.py') %}

package:
  name: ising-glass-annealer
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 1
  run_exports:
    - python
  ignore_run_exports:
    - numpy
    - scipy
    - loguru
 
requirements:
  build:
    - {{ compiler('c') }}
    - numactl-devel-cos6-x86_64

  host:
    - python
    - numpy
    - scipy
    - loguru

  run:
    - gcc_impl_linux-64
    - numactl-cos6-x86_64
    - python
    - numpy
    - scipy
    - loguru
